#!name=XAS解锁
#!desc=XASIA视频解锁20260904
#!author=suertang MMDigtal
#!homepage=https://github.com/suertang/MMDigtal

[rewrite_local]
^https?:\/\/(www\.)?xasiat\.com\/videos\/\d+\/.* url script-response-body https://raw.githubusercontent.com/suertang/MMDigtal/refs/heads/master/JSBOX/xasiat.js

[mitm]
hostname = xasiat.com, www.xasiat.com
